./scheme_test "(cond)"
#./scheme_test "(cond t)"
#./scheme_test "(cond . t)"
#./scheme_test "(cond (t . t))"
#./scheme_test "(cond (nil . t) (t t))"
./scheme_test "(cond (t 11))"
./scheme_test "(cond (nil 10) (t 11))"
./scheme_test "(cond (nil 10) (t 11) (nil 12))"
./scheme_test "(cond (10) (t 11) (nil 12))"
./scheme_test "(cond (t t nil t nil))"
#./scheme_test "(cond (t t nil t . t))"
