#./scheme_test "(if)"
#./scheme_test "(if t)"
#./scheme_test "(if t t t t)"
#./scheme_test "(if nil t t t)"
#./scheme_test "(if nil t . t)"
#./scheme_test "(if nil t . 'a)"
./scheme_test "(if t 'a)"
./scheme_test "(if nil 'a)"
./scheme_test "(if t 'a 'b)"
./scheme_test "(if nil 'a 'b)"
