./scheme_test "(progn)"
#./scheme_test "(progn . t)"
./scheme_test "(progn t)"
./scheme_test "(progn nil t)"
./scheme_test "(progn nil nil t)"
#./scheme_test "(progn t t t . t)"
#./scheme_test "(prog1)"
#./scheme_test "(prog1 . t)"
./scheme_test "(prog1 t)"
./scheme_test "(prog1 t nil)"
./scheme_test "(prog1 t nil nil)"
